let currentQuiz = null;
let answerIndex =[0,0,0,0,0,0,0,0,0,0];
let close3=document.querySelector("#close3");
close3.addEventListener("click", function(){
  mind.close();
  currentQuiz=null;
  $("#question").empty();
  $("#options").empty();
  $("#startButton").attr("value","開始作答");
})

$(function(){
    $("#startButton").on("click",function(){ 
        if(currentQuiz==null){
            currentQuiz=0;
            $("#question").text(questions[0].question)
            $("#options").empty();
            questions[0].answers.forEach(function(element,index,array){
                $("#options").append(`<input name='options'type='radio'value='${index}'>
                <label>${element[0]}</label><br><br>`);
            });
            $("#startButton").attr("value","下一題");
        }
        else{
            $.each($(":radio"),function(i,val){
                if(val.checked){
                    answerIndex[currentQuiz]=questions[currentQuiz].answers[i][1];
                    if(currentQuiz==9){
                        let finalResult = `<p>${finalAnswers[0].question}<br>${finalAnswers[0].answers[answerIndex[0]]}</p><br>`;
                        for(let i=1;i<10;i++)
                            finalResult+=`<p>${finalAnswers[i].question}<br>${finalAnswers[i].answers[answerIndex[i]]}</p><br>`;
                        $("#question").empty();
                        $("#question").append(finalResult);
                        $("#options").empty();
                        $("#startButton").attr("value","重新開始");
                        currentQuiz=null;
                    }
                    else{
                        currentQuiz=currentQuiz+1;
                        $("#question").text(questions[currentQuiz].question);
                        $("#options").empty();
                        questions[currentQuiz].answers.forEach(function(element,index,array){
                            $("#options").append(`<input name='options'type='radio'value='${index}'>
                            <label>${element[0]}</label><br><br>`);
                        });
                    }
                    return false;
                }
            });
        }      
    });
});

let questions = [
    {
        "question":"船夫說：「你可以坐上我的船，但要以身上的一樣物品交換。」那樣物品會是什麼呢？",
        "answers":[
            ["衣服",0],
            ["鞋子",1],
            ["帽子",2]
        ]
    },
    {
        "question":"船行駛到河中央，你發現船底開了一個洞。這時你會怎麼辦？？",
        "answers":[
            ["把洞堵上",0],
            ["下船游到對岸",1],
            ["請船家滑快一點",2]
        ]
    },
    {
        "question":"你上岸之後，發現有一條小路，沿著這條路一直走，你看到一間小屋，這間小屋要用密碼才能打開。下面這4組密碼，你認為哪個是正確的？？",
        "answers":[
            ["6700",0],
            ["6094",1],
            ["7450",2],
            ["6805",3]
        ]
    },
    {
        "question":"你打開門走進入後，發現屋子裡空蕩蕩的，但是在屋子中央有一個水桶。你認為水桶裡有水嗎？",
        "answers":[
            ["滿滿的一桶水",0],
            ["有一半的水",1],
            ["空水桶，沒有水",2]
        ]
    },
    {
        "question":"你走出屋子，繼續向前走，發現前面有一個瀑布。你認爲這個瀑布的水流速度是多少？",
        "answers":[
            ["靜止",0],
            ["每小時1-4公里",1],
            ["每小時5公里",2],
            ["每小時6-9公里",3]
        ]
    },
    {
        "question":"在陽光的照耀下，瀑布的水流散發著美麗的光芒。你看完這美景，你準備繼續向前走，卻發現地上有一把鑰匙串。你認為有多少鑰匙被串在一起呢？",
        "answers":[
            ["1支",0],
            ["2-5支",1],
            ["6-10支",2]
        ]
    },
    {
        "question":"再繼續向前走，突然發現眼前出現一個熱氣球。你認為這個熱氣球是？",
        "answers":[
            ["新的",0],
            ["舊的",1]
        ]
    },
    {
        "question":"你圍繞著熱氣圈走了一圈，發現旁邊有個箱子。你覺得這個箱子的尺寸是？",
        "answers":[
            ["小箱子",0],
            ["中箱子",1],
            ["大箱子",2]
        ]
    },
    {
        "question":"你覺得這個箱子的材質是什麼？",
        "answers":[
            ["塑膠",0],
            ["金屬",1],
            ["木頭",2]
        ]
    },
    {
        "question":"你準備乘著熱氣球旅行，但發現因為超重無法起飛。下面有5樣東西，你會先拋下哪樣物品來減輕重量呢？",
        "answers":[
            ["照相機",0],
            ["一個鐘錶",1],
            ["大皮箱",2],
            ["照明燈",3],
            ["罐頭",4]
        ]
    }
    
];

let finalAnswers = [
    {
        "question":"Q1：測你最害怕因為結婚失去什麼？",
        "answers":[
            ["你認為自由最可貴，所以最害怕因為婚姻失去自由。"],
            ["你認爲物質最重要，害怕婚後無法自由支配金錢。"],
            ["你害怕每天只能圍繞在柴米油鹽上打轉，害怕失去隨意支配的時間，最終變成一個平凡的黃臉婆。"]
        ]
    },
    {
        "question":"Q2：測當婚姻出現問題時，你會怎麼處理？",
        "answers":[
            ["會努力進行修復，通過冷靜的溝通解決婚姻中的問題。"],
            ["根據情況而定，如果對方犯了原則性錯誤，會選擇離婚。"],
            ["會反覆強調自己的觀點，雖然想和平解決問題，但會控制不住自己的情緒，亂發脾氣。"]
        ]
    },
    {
        "question":"Q3：測你當下對愛情的真實看法。",
        "answers":[
            ["內心深處一直藏著 喜歡的人。"],
            ["渴望被別人呵護疼愛。"],
            ["不想為了愛情放棄自由。"],
            ["很孤獨，特別想結婚。"]
        ]
    },
    {
        "question":"Q4：測你當下對生活的滿意程度。",
        "answers":[
            ["你認為目前的生活非常滿意。"],
            ["你目前的生活只有一半達到理想，還有一些地方需要努力。"],
            ["你對當下的生活很不滿意，有些問題困擾著你，搞得你壓力很大，甚至焦頭爛額。"]
        ]
    },
    {
        "question":"Q5：測你當下對性的慾望強烈程度。",
        "answers":[
            ["你幾乎沒有性慾。"],
            ["你的性慾很低。"],
            ["一般般的性慾望。"],
            ["強烈的性慾。"]
        ]
    },
    {
        "question":"Q6：測你對朋友看法。",
        "answers":[
            ["你只有一個好朋友。"],
            ["你認為朋友貴精不貴多，所以你的真心朋友雖然不多，但各個可以兩肋插刀。"],
            ["生活中有許多好朋友，但真正能說句心裡話的卻很少，這使你經常感到寂寞。"]
        ]
    },
    {
        "question":"Q7：測你對過去感情的看法。",
        "answers":[
            ["這說明你以前交往的戀人帶給你很多美好的記憶，即時你們已經分開了，你還是會永遠記住這個人。"],
            ["這說明過去的戀人帶給你很多傷害，甚至這種傷害讓你對愛情的看法產生了很大的改變。"]
        ]
    },
    {
        "question":"Q8：箱子的大小，代表你的自負程度。",
        "answers":[
            ["你比較謙遜，明白「人外有人，天外有天」的道理。"],
            ["你比較自負，但不自大。你會透過努力讓自己成為被他人羨慕的人。"],
            ["你特別自負，天老大、地老二，你就是老三。"]
        ]
    },
    {
        "question":"Q9：這道題能看出你的感情狀況。",
        "answers":[
            ["你們的感情看似很堅固，可遇到問題時一碰即碎。"],
            ["你們的感情很穩固，不過生活裡缺少一些浪漫的儀式感。"],
            ["你們目前正處於磨合期，會發現彼此觀念上存在一些差異。不過若好好溝通，這些問題都可以解決的。"]
        ]
    },
    {
        "question":"Q10：測你目前正遇到哪方面的難題。",
        "answers":[
            ["你處在迷茫之中，正在為未來而煩惱。"],
            ["你最近身體狀況不太好，如果不舒服別硬撐，快去看醫生。"],
            ["最近特別缺錢，所以正在為錢的事情發愁。"],
            ["你正被家庭問題所困擾，或者說最近和親人因為觀念不同而產生矛盾。"],
            ["你正在為異性問題而煩惱，你可能想要脫單，或正準備為感情間做下某個重要決定。"]
        ]
    }
    
];